version: "3.9"

services:
  rabbitmq:
      image: rabbitmq:management
      ports:
        - "5672:5672"
        - "15672:15672"
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=weather_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5434:5432"

volumes:
  db: